-- AlterEnum: Expand DocumentType with retailer onboarding document types
ALTER TYPE "DocumentType" ADD VALUE 'LIVE_VIDEO';
ALTER TYPE "DocumentType" ADD VALUE 'SHOP_ESTABLISHMENT';
ALTER TYPE "DocumentType" ADD VALUE 'GUMASTA_LICENSE';
ALTER TYPE "DocumentType" ADD VALUE 'SIGNATURE';
ALTER TYPE "DocumentType" ADD VALUE 'ELECTRICITY_BILL';
ALTER TYPE "DocumentType" ADD VALUE 'ADDITIONAL_ID';
ALTER TYPE "DocumentType" ADD VALUE 'FAMILY_REFERENCE';
ALTER TYPE "DocumentType" ADD VALUE 'PG_FORM';
ALTER TYPE "DocumentType" ADD VALUE 'GPS_PHOTO_OUTSIDE';
ALTER TYPE "DocumentType" ADD VALUE 'GPS_PHOTO_INSIDE';
ALTER TYPE "DocumentType" ADD VALUE 'GPS_SELFIE_DISTRIBUTOR';
ALTER TYPE "DocumentType" ADD VALUE 'DISTRIBUTOR_DECLARATION';

-- AlterTable: Add GPS metadata columns to Document table
ALTER TABLE "Document" ADD COLUMN "gpsLatitude" DOUBLE PRECISION;
ALTER TABLE "Document" ADD COLUMN "gpsLongitude" DOUBLE PRECISION;
